### ISSUE TITLE
confuses about the environment vars

### ISSUE THREAD

**Issue by yujhuang** [casetext/heroku-buildpack-firebase#1]
Hi 
when I do  git push heroku

remote: -----> Firebase app detected
remote: 
remote: -----> Getting Firebase credentials
remote:  !     Invalid email or password supplied for "(blah blah blah)".
remote:  !     Please check the values of $FIREBASE_ADMIN_USER and $FIREBASE_ADMIN_PASS.

I already gave my google credentials on heroku app settings
apparently it is not right, so what really are these two variables represent, I did not see any admin info on firebase website

thanks

**Comment by yujhuang** [comment]
I cannot find FIREBASE_AUTH_SECRET on FIREBASE

**Comment by daguej** [comment]
This buildpack is likely broken due to changes on Firebase's side (moving to the new console).

Unfortunately, we do not have any plans to continue supporting this repo, so we won't be providing a fix.
